# Generated by Django 3.2.14 on 2022-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='day',
            field=models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday')], max_length=10, null=True),
        ),
    ]
