# Generated by Django 3.2.14 on 2022-07-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0003_auto_20220706_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantable',
            name='user',
        ),
    ]
