# Generated by Django 3.2.14 on 2022-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0005_plantable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plantable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plantable',
            name='exercise',
        ),
        migrations.AddField(
            model_name='plantable',
            name='exercise_item1',
            field=models.ManyToManyField(related_name='item1', to='workoutapp.itemTable'),
        ),
        migrations.AddField(
            model_name='plantable',
            name='exercise_item2',
            field=models.ManyToManyField(related_name='item2', to='workoutapp.itemTable'),
        ),
        migrations.AlterField(
            model_name='plantable',
            name='day',
            field=models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='workoutTable',
        ),
    ]
