# Generated by Django 3.2.14 on 2022-07-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0009_alter_plantable_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantable',
            name='id',
        ),
        migrations.AddField(
            model_name='plantable',
            name='big_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
