# Generated by Django 3.2.14 on 2022-07-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0010_auto_20220708_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantable',
            name='big_id',
        ),
        migrations.AddField(
            model_name='plantable',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
